Creating a tutorial for SYCL experimental printf
zibaiwan/oneAPI-samples pull request #1
Opened 2021-08-26 18:26 UTC by zibaiwan

# Adding a New Sample(s)

## Description

Creating a tutorial for SYCL experimental printf. This tutorial demonstrates how to use printf in a DPC++ FPGA program.

## Checklist
Administrative
- [x] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [x] Enforce format via clang-format config file
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [x] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see @JoeOster for assistance)
- [x] Compile using the following compiler flags and fix any warnings, the flags are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)
- [ ] Tested using Dev Cloud when applicable

2021-08-26 18:42 UTC, zibaiwan commented
Note:

1. I have tested the code locally in PSG Linux environment. However, I haven't tested the code on windows environment yet. I am getting the access to ttolab-hld052-w.
2. I have not generated the precompiled binary on DevCloud yet. I will start to work on that once the review has passed. Edit: Mike will take care of it. Thanks!
3. There is not much I could talk about in the examining report section, so I didn't add any comment there except pointing to the report location.
4. There is a `PASS` in each print statement so that I could use the existing sycl regtest run.pl (it's grepping pass to reg.rout). I can create my own version of run.pl if this needs to be changed.
5. I haven't created regtest yet. My understanding is I should do that after this is merged, so regtest can pull it from the main branch.

2021-08-26 19:12 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +3. (Optional) As the above hardware compile may take several hours to complete, FPGA precompiled binaries (compatible with Linux* Ubuntu* 18.04) can be downloaded at TODO I will GENERATE it after the
Just change the path that you removed here to say *experimental_printf.tar* or whatever; these are generated for us.

2021-08-26 19:12 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/experimental_printf.vcxproj
> +    <ClCompile Include="src\experimental_exp.cpp" />
experimental_printf.cpp?

2021-08-26 19:12 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/sample.json
> +  "guid": "7D431C27-AC4C-4AFF-9566-5B978C3D1F5D",
Just making sure you generated this and it is not copy-pasted.

2021-08-26 19:12 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +  }
Can we put some comments here explaining the CL_CONSTANT macro and the PRINTF macro?

2021-08-26 19:12 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +       ]() [[intel::kernel_args_restrict]] {  // NO-FORMAT: Attribute
This formatting is ugly. Doesn't look like clang is obeying the `NO-FORMAT: Attribute comment`. @mdbtucker  I noticed this in some of your code too.

This line should be:

```
h.single_task<BasicKernel>([=]() [[intel::kernel_args_restrict]] {
```

Additionally. I don't think you even need kernel_args_restrict here; you have not accessor arguments...

2021-08-26 19:12 UTC, tyoungsc commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +         PRINTF("PASS Resultb: ABC%c\n", 'D');
Should we have a PRINTF that prints a variable? Maybe a kernel argument or something?

2021-08-26 19:17 UTC, JoeOster commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/sample.json
> +  "guid": "7D431C27-AC4C-4AFF-9566-5B978C3D1F5D",
This is GUID is unique to this sample

2021-08-26 19:17 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +       ]() [[intel::kernel_args_restrict]] {  // NO-FORMAT: Attribute
This is the best I was able to get from clang-format for kernel_args_restrict (see https://wiki.ith.intel.com/display/HLD/oneAPI+Code+Samples#oneAPICodeSamples-KernelArgsRestrictAttribute).  It's worse without the NO-FORMAT comment.  You can manually clean it up, but I'd rather suffer with this odd bit of formatting than have to run a manual clean-up step after running clang-format.

If you can get rid of kernel_args_restrict, you should, so I won't 'resolve' this conversation.

2021-08-31 17:48 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +3. (Optional) As the above hardware compile may take several hours to complete, FPGA precompiled binaries (compatible with Linux* Ubuntu* 18.04) can be downloaded at TODO I will GENERATE it after the
Thanks, done!

2021-08-31 17:48 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/experimental_printf.vcxproj
> +    <ClCompile Include="src\experimental_exp.cpp" />
Thanks for catching this, done!

2021-08-31 17:49 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/sample.json
> +  "guid": "7D431C27-AC4C-4AFF-9566-5B978C3D1F5D",
Yes, I generated this guid.

2021-08-31 17:52 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +  }
Thanks! I have added some comments.

2021-08-31 17:54 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +       ]() [[intel::kernel_args_restrict]] {  // NO-FORMAT: Attribute
Thanks! I got rid of intel::kernel_args_restrict.

2021-08-31 17:56 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +         PRINTF("PASS Resultb: ABC%c\n", 'D');
Thanks Tanner, I have added two kernel variables for printing.

2021-09-02 14:59 UTC, tyoungsc approved these changes
LGTM!

2021-09-02 20:56 UTC, mdbtucker requested changes

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +# Print Data Using SYCL Experimental Printf
I think we should get rid of 'Experimental' in the README here, and also remove 'experimental' from the name of the tutorial.  It's fine to mention in the text of the README that the printf function is in the 'experimental' namespace, but I don't think we need to highlight that in the title or in the name of the tutorial.  Let's just call it a 'printf' tutorial.

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +This tutorial demonstrates how to use SYCL experimental printf in a DPC++ FPGA program.
Get rid of experimental here.

Also, this is just a duplicate of the 'Description'.  How about this instead:

This tutorial shows how to use some simple macros to enable easy use of the SYCL printf() function in a DPC++ FPGA program.  This function allows printing from within code running on the FPGA.

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +// According to OpenCL C spec, the format string must be in constant address
According to THE OpenCL C spec...

must be in THE constant address...

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +// space This requires to perform "tricky" declarations of them. To simplify,
space. (missing period)

Get rid of 'This requires . . .' sentence.  Change the second sentence to 'To simplify code when invoking printf, the following macros are defined.'

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +         PRINTF("PASS Resultb: ABC%c\n", 'D');
I don't like 'PASS' at the beginning of each of these prints.  I believe this has something to do with regtests, but that's not a good reason.  I'm sure we can make the regtests work without this.

Also, please use 'Result10' and 'Result11' instead of Resulta and Resultb

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/third-party-programs.txt
> +oneAPI Code Samples - Third Party Programs File
Please remove this file from your tutorial, you have no third party components so it is not needed.

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +Compare to the Stream class, experimental::printf is a free function that can be called anywhere without needing to pass it as kernel arguements. It also has better performance in FPGA device.
We need more detail here.  'free' in what sense?  pass what as kernel arguments?  in what way is the performance better?

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +* Advantages and limitations of `sycl::ext::oneapi::experimental::printf`
This tutorial does not demonstrate any advantages or limitations of printf(), and the README does not adequately explain the advantages.  

Please add a note after 'limitations' to point readers to the section at the end of this README to see what those limitations are.

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +There are some known issues with the experimental::printf and that's why the function is in the experimental namespace. We are actively resolving those issues. The following issues only happen in har
Who is 'we' in the second sentence?  I would delete the sentence about 'actively resolving' completely.

Change the last sentence to 'The following limitations exist when using experimental::printf() on FPGA hardware:'

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +* In rare cases, if you have multiple PRINTF statements in the kernel, the order of printed data in the stdout might not obey the sequential order of those statements in the code.
Why are these cases rare?  What can cause this to happen?

2021-09-02 20:56 UTC, mdbtucker commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +* Printing string literals %s is not supported yet. You can put the string directly in the format as a workaround.
I don't understand what 'put the string directly in the format' means?  Can you provide code as an example?  Preferably as part of the tutorial .cpp code?

2021-09-09 13:32 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +# Print Data Using SYCL Experimental Printf
Thanks Mike. I agree. I got rid of most of the `experimental` now.

2021-09-09 13:32 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +This tutorial demonstrates how to use SYCL experimental printf in a DPC++ FPGA program.
Thanks Mike. Fixed.

2021-09-09 13:32 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +// According to OpenCL C spec, the format string must be in constant address
Fixed.

2021-09-09 13:34 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +// space This requires to perform "tricky" declarations of them. To simplify,
Fixed.

2021-09-09 13:34 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/src/experimental_printf.cpp
> +         PRINTF("PASS Resultb: ABC%c\n", 'D');
Thanks Mike, fixed.

2021-09-09 13:42 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/third-party-programs.txt
> +oneAPI Code Samples - Third Party Programs File
Removed.

2021-09-09 13:43 UTC, zibaiwan commented on DirectProgramming/DPC++FPGA/Tutorials/Features/experimental_printf/README.md
> +Compare to the Stream class, experimental::printf is a free function that can be called anywhere without needing to pass it as kernel arguements. It also has better performance in FPGA device.
Thanks Mike. I added some details.

2021-09-09 13:44 UTC, mdbtucker approved these changes
Thanks Zibai, looks good!

Please create a PR from this branch to the main repo (do not merge this branch into your local master).

2021-09-09 13:44 UTC, closed without merging